version: '3.7'
services:
    backend:
        image: mmaoual/top250_api:latest
        container_name: backend
        ports:
        - "8000:8000"
        depends_on:
            - mysql
    mysql:
        image: mmaoual/top250_db:latest
        container_name: mysql
        hostname: mysql
        environment:
            MYSQL_ROOT_PASSWORD: RootPassword
            MYSQL_DATABASE: top250_db
        expose:
        - "3306"
        ports:
        - "3306:3306"
